### ISSUE TITLE
Unreal Engine 4.7.0 (Preview 7) Support:

### ISSUE THREAD

**Issue by TheModdersDen** [enlight/klawr#34]
Is there a chance that you could get it to work with the Unreal Engine 4.7 (Preview 7)?

I am getting errors when compiling on this engine version...

**Comment by TheModdersDen** [comment]
I have noticed that the errors occur within the KlawrEditorPlugin, and that it fails to compile the KlawrRuntimePlugin

**Comment by Darkkitten** [comment]
I noticed that he's been inactive for awhile, not saying he's abandoned the project, he's probably busy with life..

**Comment by TheModdersDen** [comment]
OK. Thanks!

**Comment by enlight** [comment]
I've yet to switch over to 4.7, I wasn't expecting there to be so many previews :). I'll try to take a look at this in the next few days.

Note that I'm no longer actively working on this project because with Epic's continuing improvements to build times and hot reloading I'm hoping iteration times drop close to what you'd get from using a scripting layer. Also, these days Xamarin have their own C# integration for UE4, and they have far more manpower to get it done right, but of course it's not free.

**Comment by Darkkitten** [comment]
Not that we don't appricate you for all your hard work enlight :)
If I knew more C++ I'd definatly be down to being part of this project.  Because Xamarin refuses to go past UE 4.4

**Comment by enlight** [comment]
Sorry I haven't had time to fix this yet, I see the errors, and hopefully I'll have time to deal with this early next week.

**Comment by Darkkitten** [comment]
Take your time Enlight :)

**Comment by enlight** [comment]
UE 4.8 is now the minimum supported version.
